### ISSUE TITLE
Incorrect Import Path in Documentation

### ISSUE THREAD

**Issue by xigangify** [evilmartians/harmony#11]
The import path for Harmony CSS in the documentation seems incorrect. The correct path should be @import '@evilmartians/harmony/**dist**/css/orange.css';.

**Comment by 11bit** [comment]
Hello @xigangify! We have an overwrite rule for css path [here](https://github.com/evilmartians/harmony/blob/main/package.json#L20) so path without `dist` should work. 

Your bundler might not support `exports` in package.json 🤔. Where do you run it: webpack, vite, or something else?

**Comment by xigangify** [comment]
Hi @11bit. I’m using Webpack. It seems the issue might be with Webpack’s handling of the exports field in package.json. I'll update my Webpack configuration to resolve this correctly. Thanks for your help! And of course for Harmony. Soso good! 👍

**Comment by xigangify** [comment]
Thanks, done.

**Comment by 11bit** [comment]
Thanks for using Harmony. You are welcome!
