### ISSUE TITLE
Add Change Log

### ISSUE THREAD

**Issue by ai** [evilmartians/harmony#3]
We can use `ChangeLog.md` or Github Releases.

Without ChangeLog it is very hard to decide how to update the library in your project.

**Comment by 11bit** [comment]
Sure! Can you recommend any tool for releases/changelog generation or do you do it manually?

**Comment by ai** [comment]
I prefer to do it manually since changes are often differ from commit messages. Changes should be written for end-users and commits for internal usage.

**Comment by 11bit** [comment]
[Added](https://github.com/evilmartians/harmony/blob/main/CHANGELOG.md)
