### ISSUE TITLE
Create `css/index.css`

### ISSUE THREAD

**Issue by ai** [evilmartians/harmony#4]
I want to add all CSS properties with colors (it is useful for hacks or production tool with CSS Custom Properties cleaning). Can we create `index.css` which will import all other files from `css/` dir?

Of course, in docs we will promote current path `@evilmartians/harmony/css/orange.css`. `index.css` will be advanced tool.

**Comment by ai** [comment]
Here is a script which I use to clean unused colors variables https://github.com/hplush/slowreader/blob/main/web/scripts/clean-vars.ts

But other users may use PurgeCSS (we can mention it in docs).

**Comment by 11bit** [comment]
What do you think is better? File with bunch of imports for other colors or just dump everything in one file?

**Comment by ai** [comment]
I think imports is better
