### ISSUE TITLE
Rewrite first block in `README.md` to bullets

### ISSUE THREAD

**Issue by ai** [evilmartians/harmony#6]
Users always don’t have time to read carefully. This is why adding more structures to docs will improve text understandability (people will read only some part of text but still understand the message). In contrast, adding big block of text will lead to user not reading the whole block (people afraid big blocks when they don’t have time).

This is why I suggest to change this text in docs:

> With the OKLCH color space and the innovative APCA contrast algorithm, Harmony offers highly consistent color shades, previously unavailable P3 gamut colors, and precise control over text and UI element contrast.

To something like:

* Use OKLCH and APCA for consistent color shades.
* Has P3 options for modern screens.
* Was created to keep precise control over text and UI element contrast.

**Comment by 11bit** [comment]
Thanks for the advice!
