### ISSUE TITLE
Remove spaces in CSS build files

### ISSUE THREAD

**Issue by ai** [evilmartians/harmony#7]
We need to add these changes to CSS files:

```diff
-  --sand-300: oklch(…);
+  --sand-300:oklch(…);
```

The reason is very interesting.

CSS Minifiers don’t know the meaning of CSS Properties. Spaces can have some values. This is why they don’t remove any spaces in CSS Properties.

Right now `dist/app.css` of project using Harmony will have (not space between `:` and `#`):

```css
:root{--sand-50: #fffaf4;--sand-100: #f8f2eb;--sand-200: #e9e3db;--sand-300: #d4cec6;…}
```

**Comment by 11bit** [comment]
TIL. Thanks!
